// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

function parseCookies(cookieHeader: string): Record<string, string> {
  return cookieHeader.split(';').reduce((acc, pair) => {
    const idx = pair.indexOf('=');
    if (idx < 0) return acc;
    const key = pair.slice(0, idx).trim();
    const val = pair.slice(idx + 1).trim();
    acc[key] = val;
    return acc;
  }, {} as Record<string, string>);
}

function extractTokenFromCookies(cookies: Record<string, string>, supabaseUrl: string): string | null {
  const projectRef = supabaseUrl.match(/https:\/\/([^.]+)/)?.[1] ?? '';
  const baseKey = `sb-${projectRef}-auth-token`;

  // Supabase @ssr splits large cookies into chunks: sb-xxx-auth-token.0, .1, .2 etc.
  const chunkKeys = Object.keys(cookies)
    .filter(k => k.startsWith(`${baseKey}.`))
    .sort();

  if (chunkKeys.length > 0) {
    const joined = chunkKeys.map(k => cookies[k]).join('');
    try {
      const parsed = JSON.parse(decodeURIComponent(joined));
      const token = Array.isArray(parsed) ? parsed[0]?.access_token : parsed?.access_token;
      if (token) return token;
    } catch { /* fallthrough */ }
    try {
      const parsed = JSON.parse(joined);
      const token = Array.isArray(parsed) ? parsed[0]?.access_token : parsed?.access_token;
      if (token) return token;
    } catch { /* fallthrough */ }
  }

  const candidates = [
    baseKey,
    ...Object.keys(cookies).filter(k => k.startsWith('sb-') && k.endsWith('-auth-token')),
  ];
  for (const name of candidates) {
    const raw = cookies[name];
    if (!raw) continue;
    try {
      const parsed = JSON.parse(decodeURIComponent(raw));
      const token = Array.isArray(parsed) ? parsed[0]?.access_token : parsed?.access_token;
      if (token) return token;
    } catch { continue; }
  }
  return null;
}

// Extrai o refresh_token do cookie para poder renovar a sessão no servidor
function extractRefreshTokenFromCookies(cookies: Record<string, string>, supabaseUrl: string): string | null {
  const projectRef = supabaseUrl.match(/https:\/\/([^.]+)/)?.[1] ?? '';
  const baseKey = `sb-${projectRef}-auth-token`;

  const chunkKeys = Object.keys(cookies)
    .filter(k => k.startsWith(`${baseKey}.`))
    .sort();

  const rawSources: string[] = [];

  if (chunkKeys.length > 0) {
    const joined = chunkKeys.map(k => cookies[k]).join('');
    rawSources.push(joined);
    try { rawSources.push(decodeURIComponent(joined)); } catch { /* ignore */ }
  }

  const candidates = [
    baseKey,
    ...Object.keys(cookies).filter(k => k.startsWith('sb-') && k.endsWith('-auth-token')),
  ];
  for (const name of candidates) {
    const raw = cookies[name];
    if (raw) {
      rawSources.push(raw);
      try { rawSources.push(decodeURIComponent(raw)); } catch { /* ignore */ }
    }
  }

  for (const raw of rawSources) {
    try {
      const parsed = JSON.parse(raw);
      const token = Array.isArray(parsed) ? parsed[0]?.refresh_token : parsed?.refresh_token;
      if (token) return token;
    } catch { continue; }
  }
  return null;
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      throw new Error(`Missing Supabase environment variable(s): ${missing.join(', ')}.`);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');
    const cookieHeader = request.headers.get('cookie') ?? '';
    const cookies = parseCookies(cookieHeader);

    let token: string | null = null;

    if (authHeader?.startsWith('Bearer ')) {
      token = authHeader.replace('Bearer ', '');
    } else {
      token = extractTokenFromCookies(cookies, SUPABASE_URL);
    }

    if (!token) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    // Cria um cliente temporário para validar/renovar o token
    const tempClient = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    // Tenta validar o token atual
    let { data: claimsData, error: claimsError } = await tempClient.auth.getClaims(token);

    // Se o token estiver expirado, tenta renovar com o refresh_token do cookie
    if (claimsError || !claimsData?.claims) {
      const refreshToken = extractRefreshTokenFromCookies(cookies, SUPABASE_URL);

      if (refreshToken) {
        const { data: refreshData, error: refreshError } = await tempClient.auth.refreshSession({
          refresh_token: refreshToken,
        });

        if (!refreshError && refreshData?.session?.access_token) {
          // Usa o novo access_token gerado pelo refresh
          token = refreshData.session.access_token;
          const refreshed = await tempClient.auth.getClaims(token);
          claimsData = refreshed.data;
          claimsError = refreshed.error;
        }
      }
    }

    if (claimsError || !claimsData?.claims) {
      throw new Error('Unauthorized: Invalid or expired session. Please sign in again.');
    }

    if (!claimsData.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    // Cria o cliente autenticado com o token válido (pode ser o renovado)
    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    return next({
      context: {
        supabase,
        userId: claimsData.claims.sub,
        claims: claimsData.claims,
      },
    });
  },
);
