// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

function parseCookies(cookieHeader: string): Record<string, string> {
  return cookieHeader.split(';').reduce((acc, pair) => {
    const idx = pair.indexOf('=');
    if (idx < 0) return acc;
    const key = pair.slice(0, idx).trim();
    const val = pair.slice(idx + 1).trim();
    acc[key] = val;
    return acc;
  }, {} as Record<string, string>);
}

function extractTokenFromCookies(cookies: Record<string, string>, supabaseUrl: string): string | null {
  const projectRef = supabaseUrl.match(/https:\/\/([^.]+)/)?.[1] ?? '';
  const baseKey = `sb-${projectRef}-auth-token`;

  // Supabase @ssr splits large cookies into chunks: sb-xxx-auth-token.0, .1, .2 etc.
  // Try reassembling chunks first
  const chunkKeys = Object.keys(cookies)
    .filter(k => k.startsWith(`${baseKey}.`))
    .sort();

  if (chunkKeys.length > 0) {
    const joined = chunkKeys.map(k => cookies[k]).join('');
    try {
      const parsed = JSON.parse(decodeURIComponent(joined));
      const token = Array.isArray(parsed) ? parsed[0]?.access_token : parsed?.access_token;
      if (token) return token;
    } catch { /* fallthrough */ }
    // Try raw joined (base64 chunks)
    try {
      const parsed = JSON.parse(joined);
      const token = Array.isArray(parsed) ? parsed[0]?.access_token : parsed?.access_token;
      if (token) return token;
    } catch { /* fallthrough */ }
  }

  // Try single cookie candidates
  const candidates = [
    baseKey,
    ...Object.keys(cookies).filter(k => k.startsWith('sb-') && k.endsWith('-auth-token')),
  ];
  for (const name of candidates) {
    const raw = cookies[name];
    if (!raw) continue;
    try {
      const parsed = JSON.parse(decodeURIComponent(raw));
      const token = Array.isArray(parsed) ? parsed[0]?.access_token : parsed?.access_token;
      if (token) return token;
    } catch { continue; }
  }
  return null;
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');
    let token: string | null = null;

    if (authHeader?.startsWith('Bearer ')) {
      token = authHeader.replace('Bearer ', '');
    } else {
      const cookieHeader = request.headers.get('cookie') ?? '';
      const cookies = parseCookies(cookieHeader);
      const cookieKeys = Object.keys(cookies);
      console.log(`[auth] no bearer, cookie keys: ${cookieKeys.join(', ')}`);
      token = extractTokenFromCookies(cookies, SUPABASE_URL);
      console.log(`[auth] token from cookie: ${token ? 'found' : 'not found'}`);
    }

    if (!token) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
