// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    // Try getSession first
    let token: string | null = null;
    try {
      const { data } = await supabase.auth.getSession();
      token = data.session?.access_token ?? null;
    } catch { /* fallthrough */ }

    // iOS PWA fallback: session may be lost, try refreshing
    if (!token) {
      try {
        const { data } = await supabase.auth.refreshSession();
        token = data.session?.access_token ?? null;
      } catch { /* fallthrough */ }
    }

    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
)
